#https://github.com/antonbabenko/pre-commit-terraform#how-to-install
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_docs
      - id: terraform_tfsec
      - id: terraform_fmt
        args:
          - --args=-diff
          - --args=-write=true
#      - id: terrascan
#        args:
#          - --args=--non-recursive
#          - --args=--iac-type=terraform
#          - --args=--verbose
